@extends('layouts.app')

@section('title')
<title>Baby Height Chart</title>
@endsection

@section('style')
    <link rel="stylesheet" href="{{asset('css/baby/baby-chart-all-style.css')}}">
    <style>
        .collapse-charts {
            display: block !important;
        }
    </style>
@endsection

@section('user-area')
    <img src="{{asset('img/baby/baby.png')}}" class="rounded-circle">
    @isset($data)
        <a href="#"> <span>{{$data['baby_name']}}</span> </a>
    @endisset
@endsection

@section('sidebar')
@include('layouts.sidebars.baby')
@endsection

@section('content')
<div class="content">
                                          
    <div class="container">
        <div class="row">
            <div class="col-xl-9">
                <div class="chart-area">
                    <div class="word clearfix">
                       <p>
                        <?php
                            /* if($gender=='M') {

                                echo "දරුවාගේ උස ප්‍රස්ථාරය (පිරිමි)";

                            } 
                            else {

                                echo "දරුවාගේ උස ප්‍රස්ථාරය (ගැහැණු)";

                            } */

                        ?>
                        </p>
                        <div class="btn-set">
                            <button type="button" class="btn change-btn btn-sm download">බාගත කරන්න</button>
                        </div>
                    </div>
                    <div class="chart-canvas">
                        <canvas id="growth-chart-height" class="line-chart"></canvas>
                    </div>
                </div>
            </div>
            
            <div class="col-xl-3">
                <div class="container-fluid data-area">
                    <div class="row">
                        <div class="col-xl-12 col-sm-6 data-range">
                            <div class="card">
                                <div class="card-body">
                                    <h5 class="card-title">උස සටහන</h5>
                                    <p><span class="badge color-1">     </span>නියමිත උස</p>
                                    <p><span class="badge color-1"><i></i></span>මධ්‍යස්ථය</p>
                                    <p><span class="badge color-4">     </span>මිටි බවට අවදානම</p>
                                    <p><span class="badge color-2">     </span>මිටි බව</p>
                                    <p><span class="badge color-3">     </span>මිටි බව</p>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>                    
    </div>    
</div>
@endsection

@section('script')
 
    <script type="text/javascript" src="{{asset('js/charts/Chart.js')}}"></script>
    <script type="text/javascript" src="{{asset('js/jspdf.min.js')}}"></script>
    <script type="text/javascript" src="{{asset('js/baby/growth-chart-height.js')}}"></script>

    <script>
        $(function() {
            $('.inner-sidebar-menu ul li a.d-dash').addClass('active');
        }); 
    </script>

     <!-- canvas to pdf -->
     <script>
        
        $(".download").click(function() {
            
            var canvas = document.getElementById('growth-chart-height');
            
            var imgData = canvas.toDataURL();
            var doc = new jsPDF('p', 'mm', 'a4');
            doc.setFont("helvetica");
            doc.setFontType("bold");
            doc.setFontSize(12);
            doc.text(10,9, 'Baby Height Chart');
            doc.setFontSize(6);
            doc.text(170,293, 'Generated on <?php //echo date("Y, F j");?>');
            doc.setFontSize(8);
            doc.text(10,292, 'This chart was generated by <?php //echo $chart_generator;?> for <?php //echo $chart_baby;?>');
            
            var width = (canvas.width * 52) / 240;
            var height = (canvas.height * 52) / 240;

            doc.addImage(imgData, 'JPEG', 28, 15, width, height);
            //doc.output('dataurlnewwindow');     //opens the data uri in new window
            doc.save('baby-height-chart.pdf'); //Download the rendered PDF.
        });
    
    </script>
    <!-- end of canvas to pdf -->

@endsection
